apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: busybox
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/busybox
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - staging-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true