---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ns2-cloned
  namespace: ubuntu-ns2
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 10Gi
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: ubuntu-snapshot
    namespace: ubuntu
